//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class position
    {
        public int portfolio_id { get; set; }
        public int instrument_id { get; set; }
        public System.DateTime evaluation_date { get; set; }
        public int volume { get; set; }
    
        public virtual instrument instrument { get; set; }
        public virtual portfolio portfolio { get; set; }
    }
}
