//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int fldTransactionId { get; set; }
        public int fldPortfolioId { get; set; }
        public int fldInstrumentId { get; set; }
        public Nullable<int> fldTransactionTypeId { get; set; }
        public Nullable<System.DateTime> fldTradeDate { get; set; }
        public Nullable<System.DateTime> fldSettlementDate { get; set; }
        public Nullable<decimal> fldQuantity { get; set; }
        public Nullable<decimal> fldCost { get; set; }
        public Nullable<decimal> fldPrice { get; set; }
        public Nullable<System.DateTime> fldInsDate { get; set; }
        public string fldInsUser { get; set; }
    
        public virtual instrument instrument { get; set; }
        public virtual portfolio portfolio { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
