//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactions
    {
        public int portfolio_id { get; set; }
        public int instrument_id { get; set; }
        public int transaction_id { get; set; }
        public Nullable<int> transaction_type { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> volume { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual instrument instrument { get; set; }
        public virtual portfolio portfolio { get; set; }
        public virtual transaction_type transaction_type1 { get; set; }
    }
}
