//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioViewer.Models.Portfolio
{
    using System;
    
    public partial class MonthlyPerformance
    {
        public int Portfolio_ID { get; set; }
        public int Benchmark_ID { get; set; }
        public string Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> Portfolio_Performance { get; set; }
        public Nullable<double> Benchmark_Performance { get; set; }
    }
}
