USE [master]
GO

/****** Object:  Database [tutProject]    Script Date: 2018-06-27 13:43:38 ******/
CREATE DATABASE [tutProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tutProject', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\tutProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'tutProject_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\tutProject_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [tutProject] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tutProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tutProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tutProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tutProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tutProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tutProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [tutProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [tutProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tutProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tutProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tutProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tutProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tutProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tutProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tutProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tutProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [tutProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tutProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tutProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tutProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tutProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tutProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tutProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tutProject] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [tutProject] SET  MULTI_USER 
GO

ALTER DATABASE [tutProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tutProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [tutProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [tutProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [tutProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [tutProject] SET QUERY_STORE = OFF
GO

USE [tutProject]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [tutProject] SET  READ_WRITE 
GO

