USE [master]
GO

/****** Object:  Database [userDB]    Script Date: 2018-06-27 13:43:51 ******/
CREATE DATABASE [userDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'userDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\userDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'userDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\userDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [userDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [userDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [userDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [userDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [userDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [userDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [userDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [userDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [userDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [userDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [userDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [userDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [userDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [userDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [userDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [userDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [userDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [userDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [userDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [userDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [userDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [userDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [userDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [userDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [userDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [userDB] SET  MULTI_USER 
GO

ALTER DATABASE [userDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [userDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [userDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [userDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [userDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [userDB] SET QUERY_STORE = OFF
GO

USE [userDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [userDB] SET  READ_WRITE 
GO

